"""Postgres large binary for files

Revision ID: 04fe79853bd8
Revises: 20260508_01
Create Date: 2026-05-15 12:29:53.505333

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '04fe79853bd8'
down_revision: Union[str, None] = '20260508_01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('attendance_logs', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('audit_logs', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('employee_profiles', 'status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('ACTIVE', 'IDLE', 'OFFLINE', name='presence_status'),
               existing_nullable=False,
               existing_server_default=sa.text("'ACTIVE'::character varying"))
    op.drop_column('group_members', 'updated_at')
    op.alter_column('leave_requests', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('messages', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('notifications', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('reports', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('roles', 'name',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('SUPER_ADMIN', 'ADMIN', 'TEAM_LEAD', 'EMPLOYEE', name='role_name'),
               existing_nullable=False)
    op.add_column('submission_files', sa.Column('file_data', sa.LargeBinary(), nullable=False))
    op.alter_column('submission_files', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_column('submission_files', 'file_url')
    op.drop_column('submission_files', 'blob_name')
    op.alter_column('submissions', 'priority',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='task_priority'),
               existing_nullable=False,
               existing_server_default=sa.text("'MEDIUM'::character varying"))
    op.alter_column('task_updates', 'status',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.Enum('PENDING', 'IN_PROGRESS', 'REVIEW', 'COMPLETED', 'OVERDUE', name='task_status'),
               existing_nullable=True)
    op.alter_column('task_updates', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('tasks', 'status',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.Enum('PENDING', 'IN_PROGRESS', 'REVIEW', 'COMPLETED', 'OVERDUE', name='task_status'),
               existing_nullable=False,
               existing_server_default=sa.text("'PENDING'::character varying"))
    op.alter_column('tasks', 'priority',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='task_priority'),
               existing_nullable=False,
               existing_server_default=sa.text("'MEDIUM'::character varying"))
    op.drop_constraint('users_email_key', 'users', type_='unique')
    op.drop_index('ix_users_email', table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index('ix_users_email', 'users', ['email'], unique=False)
    op.create_unique_constraint('users_email_key', 'users', ['email'])
    op.alter_column('tasks', 'priority',
               existing_type=sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='task_priority'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'MEDIUM'::character varying"))
    op.alter_column('tasks', 'status',
               existing_type=sa.Enum('PENDING', 'IN_PROGRESS', 'REVIEW', 'COMPLETED', 'OVERDUE', name='task_status'),
               type_=sa.VARCHAR(length=30),
               existing_nullable=False,
               existing_server_default=sa.text("'PENDING'::character varying"))
    op.alter_column('task_updates', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('task_updates', 'status',
               existing_type=sa.Enum('PENDING', 'IN_PROGRESS', 'REVIEW', 'COMPLETED', 'OVERDUE', name='task_status'),
               type_=sa.VARCHAR(length=30),
               existing_nullable=True)
    op.alter_column('submissions', 'priority',
               existing_type=sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='task_priority'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'MEDIUM'::character varying"))
    op.add_column('submission_files', sa.Column('blob_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('submission_files', sa.Column('file_url', sa.VARCHAR(length=500), autoincrement=False, nullable=False))
    op.alter_column('submission_files', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_column('submission_files', 'file_data')
    op.alter_column('roles', 'name',
               existing_type=sa.Enum('SUPER_ADMIN', 'ADMIN', 'TEAM_LEAD', 'EMPLOYEE', name='role_name'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.alter_column('reports', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('notifications', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('messages', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('leave_requests', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.add_column('group_members', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.alter_column('employee_profiles', 'status',
               existing_type=sa.Enum('ACTIVE', 'IDLE', 'OFFLINE', name='presence_status'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'ACTIVE'::character varying"))
    op.alter_column('audit_logs', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('attendance_logs', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###
