"""add_message_fields

Revision ID: edb12a8a1795
Revises: 04fe79853bd8
Create Date: 2026-05-15 20:00:05.942344

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'edb12a8a1795'
down_revision: Union[str, None] = '04fe79853bd8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('type', sa.String(length=20), nullable=False))
    op.add_column('messages', sa.Column('content_metadata', sa.JSON(), nullable=True))
    op.alter_column('messages', 'body',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('messages', 'body',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_column('messages', 'content_metadata')
    op.drop_column('messages', 'type')
    # ### end Alembic commands ###
